### ISSUE TITLE
Header names

### ISSUE THREAD

**Issue by zs3815** [LangProc/langproc-2016-cw#12]
If we find a header name e.g. <iostream> should it just print as operator <, then an identifier iostream, then another operator > ?
Or should we say that it is 
{"Class": "HeaderName", "Text": "<iostream>", "Streamline": 1, "Sourceline": "0", "Sourcefile: "},

**Comment by m8pple** [comment]
(Sorry for the delay, thought I responded to this via email)

If I do:

    echo "#include <stdio.h>" | cpp | less

then I get something like:
````
# 1 "<stdin>"
# 1 "<built-in>"
# 1 "<command-line>"
# 1 "<stdin>"
# 1 "/usr/include/stdio.h" 1 3 4
# 29 "/usr/include/stdio.h" 3 4

<snip>

# 27 "/usr/include/machine/_default_types.h" 3 4
typedef signed char __int8_t;
````

Everything starting with a `#` is not a token, it is a pre-processor token. So when
you say "find a header" name, I assume you mean one of the `#` lines? In which
case it doesn't cause anything to print in the JSON output, but it would affect
the SourceLine and SourceFile of the next token to be output.

So the first token seen from the source above would be:
````
{ "Class":"keyword", "Text":"typedef", "SourceLine":27, "SourceFile":"/usr/include/machine/_default_types.h"}
````
(Note, typing this free-hand, so there may be typos).

BTW, note that the line numbers (e.g. SourceLine) are numbers, not strings.

**Comment by zs3815** [comment]
That all made sense apart from why is the source line 3 in your example, would it not be 27? Also when you say that the source line is a number not a string, does that mean it should not print in quotes in JSON?

**Comment by m8pple** [comment]
You're right, it should be 27 - sorry, student came in and I got distracted while
finishing the comment.

For the line numbers: indeed, it should not print in quotes. JSON supports primitive
values (terminals!) of string, number, boolean, and the line number should be a number
rather than a string (I think that is what the examples show).

**Comment by louiskueh** [comment]
Just to confirm, our inputs from *stdin* would have "" for SourceFile and SourceLine set to 0?

Or is SourceFile the name of the file e.g. "tmp.c" and Sourceline = Streamline?

**Comment by m8pple** [comment]
Yes, for things coming from `stdin` where you haven't seen any filename yet, the SourceFile would
be "".

And if you don't see any `#` directives, then it will always be the case that SourceLine==StreamLine.

However, the SourceLine would still start at 1, so the first token appears on line 1, not on line 0.
e.g. if you go into a text editor it won't let you go to line 0 (well, most editors). Remember that
the whole point of the SourceFIle/SourceLine attributes is that we can go back from a token that
causes an error to the file and location that it appeared in. So if you take a token from the
JSON output with a non-empty filename, you should be able to go to the file and line it
indicates and find that token there. If the token has an empty token, then it should appear
in the given position in the stream coming in over `stdin`.

In terms of getting a filename like `tmp.c`, part of the point of `stdin` is that it is unnamed,
so unless you are given a filename via a `#` you don't know the original source of the file.
