### ISSUE TITLE
Soft Test

### ISSUE THREAD

**Issue by luisi-at** [LangProc/langproc-2016-cw#15]
Turns out I messed up my file structure and so did not get a build for the soft test. Would you be able to do another one before 2200?

**Comment by m8pple** [comment]
Sorry, didn't see this till now, and it's a bit late to be
useful.

That said, I'm not too keen on doing last minute runs anyway,
as the goal is to give enough information to avoid any
show-stoppers and allow people to move on with other
things, not to become part of the edit-test cycle.

Note that I'm doing these tests in exactly the Vagrant
machine that you have, so you should be able to run
roughly the same steps if you want to replicate it
(given enough squinting at the logs).

David Thomas
