### ISSUE TITLE
Empty Scope in an empty function

### ISSUE THREAD

**Issue by martinferianc** [LangProc/langproc-2016-cw#21]
The spec says that we can make use of extra scopes. I wanted to ask if this would also be a valid output, given that the function is empty.

Input: 
```
int x()
{}
```

Output: 

```
<Function id="x">
        <Scope/>
    </Function>
```

**Comment by m8pple** [comment]
Yup, that is fine.

Any level of extra scoping is equivalent to adding a {}
pair, so anywhere that you could add {} and it wouldn't
change the meaning of the C code, you could also add a
<Scope />, or anywhere that you could replace `X` with
{ `X` } you could also add a <Scope>X</Scope>.

David Thomas

**Comment by martinferianc** [comment]
Thank you!
