### ISSUE TITLE
parser

### ISSUE THREAD

**Issue by yg4815** [LangProc/langproc-2016-cw#22]
I am quite confused about why the following code 
int zz(int a, int b, int c)
would result in:
 \<Parameter id="a" />\<Parameter id="b" />
 \t               \<Parameter id="c" />
instead of:
\<Parameter id="a" />\<Parameter id="b" />\<Parameter id="c" />

**Comment by m8pple** [comment]
It's very unlikely that a tool would generate such code, the point is
more that it is legal. XML is a container format for structured data,
so it doesn't care about (most) whitespace.  XML is a language
just like C, so it has a notion of tokens and grammar, and each
distinct XML document has an infinite number of character-based
representations (just like each C program has an infinite number
of character-based variants that vary only by whitespace).

It is the same as whether this:
````
int zz(int a, int b, int c)
{ return a+b+c; }
````
is the same as this:
````
int zz(int a, int b,
    int c)
{ return a+b+c; }
````
or this:
````
int zz(int a,int b,int c){return a+b+c;}
````
