### ISSUE TITLE
empty scope

### ISSUE THREAD

**Issue by yg4815** [LangProc/langproc-2016-cw#23]
Given that additional scope nesting levels and extra empty scopes are allowed, you may wonder how it is possible to tell whether the scoping is correct. This comes down to the lifetime of variables within the original C program.  
Does this statement mean we can manually add a empty scope outside the \<program> ... \</program>?

**Comment by m8pple** [comment]
If you mean something like:
````
<?xml version="1.0"?>
<Program>
</Program>
<Scope/>
```
then no (note that `program`!=`Program`).

The Program element is the top-level element, and there can only be
one top-level element, just like there is only one top-level symbol in your
C grammar (hopefully!).

If you mean something like:
````
<?xml version="1.0"?>
<Program>
<Scope/>
</Program>
```
then that doesn't work either, as we have the text:

> <Scope> : Appears within either a Function or another Scope

so not within a Program. You can work out the grammar of the XML
document as (roughly):
````
Program : (Function | Variable) *

Function : Parameter* ( Scope | Variable )*

Scope : (Scope | Variable ) *
````
