### ISSUE TITLE
compilation-run

### ISSUE THREAD

**Issue by yg4815** [LangProc/langproc-2016-cw#25]
Will you provide any compilation-run before the deadline? If yes, what is the deadline for those.

**Comment by m8pple** [comment]
Sorry, didn't see this over the weekend.

I did a pull and compilation-run late on Sunday, which I just pushed through
manually (it got stuck due to a bug).

Looking at my schedule, I can commit to doing runs at (or just after):
- Today (Monday) at 18:00
- Tomorrow (Tuesday) at 14:00
