### ISSUE TITLE
Extra declaration in flex file

### ISSUE THREAD

**Issue by ymherklotz** [LangProc/langproc-2016-cw#26]
In the Parser lab, the flex file had this line included at the top:

`extern "C" int fileno(FILE *stream);`

Is this a necessary inclusion? Because if I remove it I don't get the error that it has not been declared in the scope.

My parser and compiler for the coursework were working fine with this line included on my machine, however, I tried it in the vagrant environment and it didn't seem to compile anymore. 
I get the following error:

`'int fileno(FILE*)' has a different exception specifier`

**Comment by m8pple** [comment]
(Sorry, didn't see this via my inbox, so didn't see it till now in the github page)

I have to admit, I can't quite remember why I put the explicit `fileno` declaration
in the lexer (I did it over the summer, and my commit history doesn't tell
me why). In principle it should come in just by using `#include <stdio.h>`,
so I must have been fixing something specific to the Vagrant and lab Ubuntu
configuration.

An exception specifier is a C++ thing, which says which functions could
throw errors. I would guess that in `<cstdio>` it is declared as something
like:
````
int fileno(FILE * ) throw(); // Indicate it doesn't throw exceptions
````
It's possible that compiling the lexer with C++ it gets a C++ version
in stdio, but then the explicit version gives a version without the
exception specification.

I'll investigate during marking if there are any such errors; it's definitely
something I can easily fix, though I'll have to decide whether it counts as
my fault for using poor practises, or insufficient/late testing on the target platform.

**Comment by ymherklotz** [comment]
Great thank you, that's fine then. I thought there might have been a definite reason for it, and that without it, it wouldn't run on the target platform. I did remove it in the end as it made no difference on my machine and worked fine without it in vagrant.
