### ISSUE TITLE
Can we use an assembler for final step?

### ISSUE THREAD

**Issue by ps-george** [LangProc/langproc-2016-cw#28]
I am outputting .s mips assembly code now.

Are we supposed to output an object file?

Can we use gcc to compile the assembly for this?

**Comment by m8pple** [comment]
Yes, definitely. Your job is to only produce the assembly. After that
the gnu assembler (probably in the guise of gcc) can handle it.

Writing an assembler is in some ways a fairly straightforward thing,
but emitting linkable object files or an elf executable is actually quite
tricky. The key learning outcome is the knowledge of compilation,
and lowering of languages, so stopping at assembly works fine.

**Comment by ps-george** [comment]
Thank goodness.
