### ISSUE TITLE
SourceLine and StreamLine

### ISSUE THREAD

**Issue by divyanshmanocha** [LangProc/langproc-2016-cw#4]
Would it possible to provide an example regarding the difference between the two? Also should StreamLine display the corresponding line number on the origin source file (not pre-processed)?

Also I cannot find more information about this in 'See comments on the pre-processor'

**Comment by m8pple** [comment]
For SourceLine (which is the one with the "see comments"), it will be the source line
as indicated by gcc. So whatever gcc considers to be the source line will be the
contents of `SourceLine`.

For StreamLine, the documentation is:
````
The line number the token appears on, in terms of the input stream. The first line number is 1. This number increases regardless of any remapping indicated by pre-processor directives.
````
Given there is only a single input stream (regardless of pre-processor directives),
isn't this un-ambiguous?

I can give an example, but need to see where the ambiguity is (I'm not saying there isn't any).

**Comment by tnugent97** [comment]
I am also confused about this.

_StreamLine_ makes sense but I can't find _SourceLine_ mentioned in the gcc documentation, although maybe I need to look a little harder.

**Comment by divyanshmanocha** [comment]
I still have some trouble understanding SourceLine as well, still. Is it related to the pre-processed file that the lexer is currently considering? Or is it just ignoring the hashtags, for one reason or another. It may be useful, perhaps, to explain the purpose of the variable?

**Comment by tnugent97** [comment]
So as far as I understand it now, streamLine is just the line number of the pre-processed file, which always increases by 1 no matter what.
SourceLine is the same, but does not increase when the line starts with a # (indicating something that has been put there by the preprocessor).
Is this correct?

**Comment by m8pple** [comment]
I think @tnugent97 's interpretation is correct.
- StreamLine increases by one for each new line observed in the pre-processed file
- SourceLine increases by one for each line that does not contain a `#line` directive
- `#line` directives may change the current value of SourceLine
