### ISSUE TITLE
C characters

### ISSUE THREAD

**Issue by luisi-at** [LangProc/langproc-2016-cw#5]
How do you want a single character defined? As a constant like the numbers are defined or a character literal?

**Comment by m8pple** [comment]
As a constant, in with the integers. The logic is that a character constant is
explicitly not a string literal.

I'll clarify in the text, as it could be confusing.

**Comment by tnugent97** [comment]
Sorry to reopen this, but the ANSI spec says that a char is defined as follows:
```
An integer character constant is a sequence of one or more multibyte characters enclosed in
single-quotes. as in ’ x’ or ’ ab’
```
but I thought chars could only contain one character (isn't that kind of the point of them?).
Is this something that is then rejected in the parser?

**Comment by m8pple** [comment]
Characters (and strings) are much more complicated than the simple ASCII
world, as you might need to build characters for which there is no particular
way of building it. That is mostly covered by the explicit octal
method (e.g. `'\x45\x32'`) for building up a character, which _usually_ means
that you build the character from MSB to LSB. So from memory, the 
preceding would turn into the character 0x4532 (whether that is a real
character, I'm not sure).

The multi-char stuff is another way of building up multi-byte characters
from ASCII ones, so `'E2'` would (maybe) be the same as 0x4532. However,
it is all _implementation defined_, e.g. search for implementation defined here:
http://en.cppreference.com/w/c/language/character_constant

Regardless of what they actually mean, from a lexing point of view
it is relatively easy to deal with. If your lexer can deal with the
single character literals `'` and `\`, it can probably also deal with
such literals. To be honest, I don't have any such literals in my
test bank though....

In modern C versions one would use unicode code-points as a way of
getting well-defined characters, but adoption of unicode in C/C++
came a few years after C89/90. When Windows NT was released
in the early 90s, it was the first OS to actually support it, and most
compilers (beyond MSVC) didn't pick it up till a fair bit later.
