### ISSUE TITLE
Distinction between "operators" and "punctuation"

### ISSUE THREAD

**Issue by tnugent97** [LangProc/langproc-2016-cw#7]
In the specification you mention this:

```
Note: This does not make any distinction between "operators" and "punctuators" which you will see in some C grammars. We will ignore the distinction and only have an operator class.
```

But is not beneficial for us to implement these types of distinctions so it is easier to write the compiler?
Or do you differentiate between these types of things in the parser?

Otherwise you have the question of at which point do you stop differentiating between things. I could have 32 return types for each type of keyword .etc

Thanks in advance

**Comment by m8pple** [comment]
The division of things into classes is fairly arbitrary, and is mainly intended to make
people care about the different types of actions they take in response to the
tokens. So the thinking is:
- Constants represents fixed-size values (no dynamic allocation needed)
- String literals are variable-sized, so they need lifetime management
- Keywords are _mostly_ involved in statements and declarations (there are
    obvious exceptions)
- Operators are _mostly_ involved in expressions (there are also many exceptions)

So the current classes are designed to try to at least get people to think about the
differences in terms of token attributes and the way the tokens are used, without
adding too much extra load purely for assessment porpoises (that's a dolphin
with a clip-board; you mostly find them in schools).

I pondered adding the distinction between operators and punctuators,
but there are diminishing returns in terms of cognitive load. Many people
will find that the punctuators mostly feel like operators, and find the
distinction not useful, so it felt like more classes are not useful. A similar
argument can be made for adding separate classes for float vs integer
literals, or even for float vs double literals.
