### ISSUE TITLE
Example of StringLiteral output confusion

### ISSUE THREAD

**Issue by MK2020** [LangProc/langproc-2016-cw#8]
$ cat wibble.c
z="wibble"
$ cat wibble.c | bin/c_lexer
[ { "Class" : "Identifier",    "Text": "z" },
  { "Class" : "Operator",    "Text": "=" },
  { "Class" : "StringLiteral",    "Text": "z" }
]

With the above, why would the preferred output of the stringliteral be "z" and not the string "wibble"?

Thanks

**Comment by m8pple** [comment]
Because I messed up the example. I think maybe I confused the "wrong" example
from last year that I used in the slides with an example from my reference, and then
turned it into JSON. Twice, apparently.

Thanks, I'll fix it.
