### ISSUE TITLE
What to print for SourceFile if it is from stdin?

### ISSUE THREAD

**Issue by Carotti** [LangProc/langproc-2016-cw#9]
At the moment, my lexer simply prints "stdin".

Obviously in a more real-world compiler situation, you would give the compiler the filepath of the files you want to compile, so it would know. In this case however, what should the tokens that come directly from stdin (ie, not included from another file) have as their SourceFile property?

**Comment by Carotti** [comment]
(If it is guaranteed that the input file will contain the necessary preprocessor output, then this isn't really an issue..)

**Comment by m8pple** [comment]
I think that's covered by this clause?:

> Use the default filename "" as the SourceFile if there is no information provided by a pre-processor.

I don't mind adding an alternative like `<stdin>` if it makes things look nicer (I can't change
the original spec to be wrong).

Plus, it's not always the case that real compilers have an actual named source file, particularly
when doing code generation. I've ended up doing things like this a few times:

    ./my_code_gen params | gcc -x - -o - | ssh $HOST "cat - > wibble; chmod u+x wibble; ./wibble"

Try doing `gcc -E -` and typing in some code, then ctrl+d.
